package com.querybricks.processor.generation;

import com.squareup.javapoet.JavaFile;
import java.io.IOException;
import javax.annotation.processing.Filer;

/**
 * Represents a source file generated by JavaPoet and writes it to Filer.
 */
public final class PoetSourceFile {
    private final Filer filer;
    private final String packageName;
    private final GeneratedClass origin;

    /**
     * Constructor.
     * @param filer Compilation Filer object to write generated file.
     * @param packageName Package where class should be generated.
     * @param origin The generated class specification.
     */
    public PoetSourceFile(Filer filer, String packageName, GeneratedClass origin) {
        this.filer = filer;
        this.packageName = packageName;
        this.origin = origin;
    }

    /**
     * Saves the generated class to the filer.
     */
    public void save() {
        try {
            JavaFile.builder(this.packageName, this.origin.spec())
                .indent("    ")
                .build()
                .writeTo(this.filer);
        } catch (IOException e) {
            throw new IllegalStateException(
                "Failed to write generated class: " + packageName,
                e
            );
        }
    }
}
